package config

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Render produces the config.yml vision_processor reads for camera c: the
// document's defaults with c's own config merged over, plus the values
// derived from the document as a whole (cam_id, camera_amount, and the seed's
// line_corners). sourcePath is named in the header comment.
//
// This is the stand-in transport until vision_processor accepts config over
// the network; vision_processor hot-reloads color/thresholds/tracking/debug
// from it and needs a restart for everything else.
func Render(doc Document, c Camera, sourcePath string) ([]byte, error) {
	merged := doc.Effective(c)
	merged["cam_id"] = c.CameraID

	geom, _ := merged["geometry"].(map[string]any)
	if geom == nil {
		geom = map[string]any{}
		merged["geometry"] = geom
	}

	geom["camera_amount"] = doc.CameraCount()
	delete(geom, "line_corners")

	if c.Seed != nil && len(c.Seed.LineCorners) == 4 {
		corners := make([]flowPair, len(c.Seed.LineCorners))
		for i, p := range c.Seed.LineCorners {
			corners[i] = flowPair(p)
		}

		geom["line_corners"] = corners
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# Generated by vision-processor-gui from %s.\n# Edit that file (or use the GUI) instead; changes here are overwritten.\n", sourcePath)

	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)

	if err := encoder.Encode(merged); err != nil {
		return nil, err
	}

	if err := encoder.Close(); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// flowPair encodes as [x, y] rather than a two-line block sequence.
type flowPair [2]int

func (p flowPair) MarshalYAML() (any, error) {
	node := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
	for _, v := range p {
		node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: fmt.Sprint(v)})
	}

	return node, nil
}

// renderAll regenerates every camera's config.yml that has a ConfigPath,
// returning an error message per camera_id that failed.
func renderAll(doc Document, sourcePath string) map[int]string {
	failures := map[int]string{}

	for _, c := range doc.Cameras {
		if c.ConfigPath == "" {
			continue
		}

		data, err := Render(doc, c, sourcePath)
		if err == nil {
			_, err = writeIfChanged(c.ConfigPath, data)
		}

		if err != nil {
			failures[c.CameraID] = fmt.Sprintf("render %s: %v", c.ConfigPath, err)
		}
	}

	return failures
}

// writeIfChanged writes data to path only if it differs from what's there,
// so an unchanged render doesn't bump the mtime vision_processor polls.
func writeIfChanged(path string, data []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, data) {
		return false, nil
	}

	return true, atomicWrite(path, data)
}

// errReadOnly is an existing file with no write permission, such as the
// reference files in the repo's config/ directory.
var errReadOnly = errors.New("file is read-only")

// atomicWrite replaces path via a temp file and rename, so a reader (the
// watcher, vision_processor's own reload) never sees a half-written file.
// A rename replaces a file whatever its permissions, so a read-only file is
// refused here instead.
func atomicWrite(path string, data []byte) error {
	if info, err := os.Stat(path); err == nil && info.Mode().Perm()&0o222 == 0 {
		return fmt.Errorf("%s: %w", path, errReadOnly)
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}

	defer os.Remove(tmp.Name()) // no-op once renamed

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()

		return err
	}

	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()

		return err
	}

	if err := tmp.Close(); err != nil {
		return err
	}

	return os.Rename(tmp.Name(), path)
}
